root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ./cmd/api"
bin = "./tmp/main"
include_ext = ["go"]
exclude_dir = ["vendor", "tmp", "build"]
delay = 1000
kill_delay = 500

[log]
time = true

[color]
main = "yellow"
build = "cyan"
runner = "green"

[screen]
clear_on_rebuild = true
