services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - redis
    networks:
      - iam-bridge-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    networks:
      - iam-bridge-network

networks:
  iam-bridge-network:
    driver: bridge
