// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package di

import (
	"github.com/google/wire"
	"github.com/zahidhasanpapon/iam-bridge/internal/config"
	"github.com/zahidhasanpapon/iam-bridge/internal/server"
	"github.com/zahidhasanpapon/iam-bridge/pkg/logger"
)

// Injectors from di.go:

// InitializeApp initializes the application
func InitializeApp() (*server.Server, error) {
	configConfig, err := config.NewConfig()
	if err != nil {
		return nil, err
	}
	loggerLogger, err := logger.NewLogger(configConfig)
	if err != nil {
		return nil, err
	}
	serverServer, err := server.NewServer(configConfig, loggerLogger)
	if err != nil {
		return nil, err
	}
	return serverServer, nil
}

// di.go:

// ProviderSet is a provider set for wire
var ProviderSet = wire.NewSet(config.ProviderSet, logger.ProviderSet, server.ProviderSet)
